language: r
sudo: required
cache: packages
dist: trusty
warnings_are_errors: false

jobs:
  include:
  - r: devel
  - r: release
  
before_install:
  - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" > ~/.Rprofile

apt_packages:
 - libfftw3-dev

r_packages:
 - fftw
 - covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  