# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

# Nabbed from https://github.com/RcppCore/Rcpp/blob/master/.travis.yml
# modified from devtools

# this is a temporary hack at a solution, until R is supported by Travis
language: c

env:
  global:
    # set to force failure with warnings
    #- WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=1
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - CRAN="http://cran.us.r-project.org"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libfftw3-dev
  - ./travis-tool.sh install_aptget r-cran-runit
  - ./travis-tool.sh install_r fftw
  - ./travis-tool.sh install_r Rcpp RColorBrewer signal zoo bspec ggplot2 knitr multitaper plyr RSEIS rbenchmark reshape2
#  - ./travis-tool.sh install_github hadley/devtools

script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

