language: r
r:
 - release
sudo: required
cache: packages
warnings_are_errors: false
dist: trusty

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

apt_packages:
 - libfftw3-dev

r_packages:
 - fftw
 - covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  