#!/bin/sh
set -e
PKG="rlpSpec"
TGZ="${PKG}_0.1-0.tar.gz"
##
rm -rf ${PKG}.Rcheck
rm -f ${PKG}/src/*.*o
##
case $1 in
	p)rm -f ${PKG}.pdf; R CMD Rd2pdf ${PKG};;
	b) R CMD BUILD ${PKG};;
	c) R CMD CHECK --no-multiarch ${TGZ};;
	cc) R CMD CHECK --as-cran --no-multiarch ${TGZ};;
	ce) R CMD CHECK --as-cran --no-multiarch --no-examples ${TGZ};;
	i) R CMD INSTALL --no-multiarch ${TGZ};;
	bc)$0 b; $0 cc;;
	bce)$0 b; $0 ce;;
	bcei)$0 bce; $0 i;;
	*)$0 bcei;;
esac
