#!/bin/sh
set -e
PKG="rlpSpec"
TGZ="${PKG}_0.1-0.tar.gz"
##
rm -rf ${PKG}.Rcheck
rm -f ${PKG}/src/*.*o
##
case $1 in
	r) R CMD BUILD ${PKG};;
	b) R CMD CHECK --no-multiarch ${TGZ};;
	bc) R CMD CHECK --as-cran --no-multiarch ${TGZ};;
	bce) R CMD CHECK --as-cran --no-multiarch --no-examples ${TGZ};;
	rb)$0 r; $0 b;;
	rbc)$0 r; $0 bc;;
	rbce)$0 r; $0 bce;;
	*)$0 rbce;;
esac
