wd <- getwd()
setwd("~/kook.processing/R/dev/packages/rlpSpec/figures")
source("../rsrc/S3_plot.R")
source("../rsrc/S3_print.R")
source("../rsrc/S3_summary.R")
source("../rsrc/demo_local.R")
source("../rsrc/func_psdcore.R")
source("../rsrc/func_pspectrum.R")
source("../rsrc/func_qualcon.R")
source("../rsrc/func_riedsid.R")
source("../rsrc/func_supps.R")
source("../rsrc/func_whiten.R")
source("../rsrc/usemethods.R")
setwd(wd)
