#
#       !! autogenerated !!
#
#       .sourceloads.R        
#       makeloads.sh      Thu Aug 16 21:22:38 PDT 2012
#       /Users/abarbour/nute.processing/development/rlpSpec/rsrc
#
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/S3_plot.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/S3_print.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/S3_summary.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/demo_local.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/dev_func_boundslope.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/dev_func_tapsum.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_psdcore.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_pspectrum.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_qualcon.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_riedsid.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_supps.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/func_whiten.R")
source("/Users/abarbour/nute.processing/development/rlpSpec/rsrc/usemethods.R")
