\documentclass{article}
% sweave fig help:
% http://users.stat.umn.edu/~geyer/Sweave/foo.pdf
% borrowing design from roxygen -- AJB Jan 13
%% \VignetteIndexEntry{rlpSpec Overview Vignette}
\usepackage[utf8]{inputenc}
\usepackage{fancyvrb}
\usepackage[pdfborder={0 0 0}]{hyperref}
\usepackage{url}
\usepackage{upquote}
\usepackage{graphicx}
\usepackage{grffile}
\usepackage{float}
\usepackage{natbib}
\newcommand{\Rcmd}[1]{\texttt{#1}}
\newcommand{\rlp}[0]{\Rcmd{rlpSpec}}
\newcommand{\naive}[0]{na\"{\i}ve}
%% path, filename, caption, label
\newcommand{\listing}[4]{        %
  \begin{figure}[H]              %
    \centering                   %
    \VerbatimInput[numbers=left, %
      frame=single,              %
      label=#2]{#1}              %
    \caption{#3}                 %
    \label{#4}                   %
  \end{figure}                   %
}
\author{Andrew J. Barbour \url{<andy.barbour@gmail.com>}
and Robert L. Parker}
\title{An overview of \rlp{}: Adaptive sine multitaper power spectral
density estimation}
\begin{document}
\maketitle
\begin{abstract}
  The purpose of this vignette is to provide an overview of the
  features included in \rlp{}, which allow the
  user to compute sophisticated power spectral
  density (PSD) estimates for a univariate series, with very little tuning effort.
  The sine multitapers are used in which
  the number of tapers varies with spectral shape, according
  to the optimal value proposed by \citet{rs1995}.
  The adaptive procedure
  iteratively refines the optimal number of tapers at each frequency,
  which, assuming convergence, will produce
  spectra with significantly
  reduced variance (compared to \naive{} estimators),
  and minimum biasing effects.
  Resolution and uncertainty in a multitaper scheme
  are controlled by the number of tapers used.
  This means we do
  not need to resort to either windowing methods 
  which inherently degrade resolution of low-frequency features
  (e.g. Welch), or smoothing kernels 
  which can badly distort important features without careful tuning
  (e.g. Daniell, as in \Rcmd{stats::spec.pgram}).
  In this sense
  \rlp{} is best suited for data having
  spectra with both large dynamic range and strong, sharply changing features.
\end{abstract}
\tableofcontents
\section{Quick start: A minimal example.}

%\listing{graph.R} % src
%	{graph} % src label
%	{Call matrix}	% caption
%	{fig:callmat}	% fig label

First load the package into the namespace:
%<<echo=FALSE, eval=TRUE>>=
%#opar <- par(no.readonly = TRUE)
%par(mar=rep(2,4), oma=rep(2.,4))
%@ 
<<keep.source=TRUE, eval=TRUE>>=
library(rlpSpec)
@ 
We now need a dataset to analyze.
Among the datasets included in \rlp{} is a subset of
the Magnetic Satellite (MAGSAT) mission \citep{langel1982}.
Specifically, we have included along-track measurements
of horizontal magnetic-field strength from a gimballed, airborne magnetometer,
sampled once every kilometer, which means the spectrum may represent
crustal magnetization with wavelengths longer than 2 km.
<<keep.source=TRUE, eval=TRUE>>=
data(magsat)
@ 
The format of the data set is a \Rcmd{data.frame} with four
sets of information:
<<keep.source=TRUE, eval=TRUE>>=
names(magsat)
@ 
The \Rcmd{raw} and \Rcmd{clean} names represent raw
and edited intensities respectively, expressed in units of nanoTesla; 
\Rcmd{mdiff} is the difference between them.
The difference between them is a matter of just a few points
attributable to instrumental malfunction. 
<<eval=TRUE, echo=TRUE>>=
subset(magsat, abs(mdiff)>0)
@
These deviations can,
as we will see, adversely affect the accuracy of any PSD estimate,
multitaper or otherwise.

Setting aside any discussion regarding sample stationarity,
we can find power spectral density (PSD)
estimates for the two series quite simply:
<<eval=TRUE, echo=TRUE>>=
psdr <- pspectrum(magsat$raw)
psdc <- pspectrum(magsat$clean)
@
Each  \Rcmd{pspectrum} command calculates a pilot PSD, followed by four
iterations of refinement (the default).
With each iteration
the number of tapers is adjusted 
to the optimal number, based on the weighted
spectral derivatives, following \citet{rs1995}.
In general, spectral variance is reduced
with sequential refinements, but is not necessarily quaranteed to converge.
Note that in the example
the sampling frequency of both series
is km$^{-1}$, so we need not change the sampling rate
argument.

Let's now visualize the two PSD estimates, recalling that the difference between
the \Rcmd{raw} and \Rcmd{clean} samples is a mere two points.
\footnote{
Note that \Rcmd{pspectrum} returns
an object with class \Rcmd{spec}, so we have access to methods 
within \Rcmd{stats}, including \Rcmd{plot.spec}.
%<<eval=TRUE, echo=TRUE>>=
%class(psdc)
%@
}
%%
\begin{figure}[htbp!]
\begin{center}
%<<eval=TRUE, fig=TRUE, echo=TRUE, width=8, height=4.5, label=fig_magsat>>=
<<eval=TRUE, fig=TRUE, echo=TRUE, label=fig_magsat>>=
plot(psdc, log="dB")
lines(psdr$freq, 10*log10(psdr$spec), col="red")
legend("bottomleft",c("magsat$raw","magsat$clean"),col=c("red","black"),lty=1,lwd=2)
@
\end{center}
\caption{Comparison of power spectral densities for the \Rcmd{MAGSAT} data
included with \rlp{}.}
\label{fig:one}
\end{figure}
%%
Figure \ref{fig:one} compares the spectra for the \Rcmd{raw} and \Rcmd{clean} 
samples.  This plot shows a
drastic improvement in shape between the two series,
simply because the large outliers have been removed.
The \Rcmd{clean} PSD shows the
very red spectrum typical of geophysical processes \citep{agnew1992}.
It also shows a rolloff in signal
somewhere around the 20 kilometer wavelengths; whereas, the 
\Rcmd{raw} PSD looks highly unrealistic at higher wavelengths, and
shows some curvature bias at low frequencies.

\section{Comparisons with other methods}

As we have shown in the MAGSAT example, 
improved understanding of the physics behind the signals in the data
is of great concern.
Assuming a sample is free of non-physical points, how do
PSD estimates from \rlp{}
compare with other methods?

\subsection{\Rcmd{stats::spectrum}}
Included in the core distribution of R is \Rcmd{stats::spectrum}, which
accesses \Rcmd{stats::spec.ar} or \Rcmd{stats::spec.pgram} for either
parametric and non-parametric estimation, respectively.  Our method is
non-parametric; hence, we will compare to the latter.

Included in \rlp{} is
an option
to compare the 
results with a \naive{} estimator--the raw periodogram--from within the
spectrum calculator, \Rcmd{psdcore}.
In R this estimator is equivalent to running:
<<eval=FALSE, echo=TRUE>>=
spec.pgram(X, pad=1, taper=0, detrend=FALSE, demean=FALSE, plot=F)
@
which \Rcmd{psdcore} also calculates.

As a matter of bookkeeping, we must deal with the working environment
accessed by \rlp{} functions.
Specifically, \Rcmd{psdcore} does not clear anything from the working
environment, but accesses some of its content under certain conditions; 
hence, we must first manually clear the environment to prevent bogus results:
<<eval=TRUE, echo=TRUE>>=
str(rlp_envStatus())
rlpSpec:::rlp_envClear()
str(rlp_envStatus())
@
and then re-calculate the multitaper PSD and the
raw periodogram.  The results are shown in Figure \ref{fig:two}.

\begin{figure}[htbp!]
\begin{center}
%<<eval=TRUE, echo=TRUE, fig=TRUE, width=8, height=6, label=fig_magsat_naive>>=
<<eval=TRUE, echo=TRUE, fig=TRUE, label=fig_magsat_naive>>=
ntap <- psdc$taper
psdcore(magsat$clean, ntaper=ntap, plotpsd=TRUE)
@
%str(rlp_envStatus())
\caption{Top: Comparison between \naive{} and multitaper PSD estimators for the 
clean \Rcmd{MAGSAT} data. The frequency axis is in units of $\log_{10}$ km$^{-1}$,
and power axis is in decibels.
Bottom: The spatial series used to estimate the PSDs.}
\end{center}
\label{fig:two}
\end{figure}

\subsection{\Rcmd{multitaper::}}

\section{Assesing spectral properties}
In a multitaper scheme,
the computation of resolution and uncertainty (shown as blue lines
in Figure \ref{fig:one} depends on the 
the number of tapers; hence, the methods internal to \Rcmd{plot.spec}
are not appropriate.

%%
\section{Call overview}

\begin{figure}[htbp!]
 \centering
 \includegraphics[width=0.6\textwidth]{yuml_d.png}%%
 \includegraphics[width=0.3\textwidth]{yuml_n.png}
 \caption{Simplified call graph.}
 \label{fig:calls}
\end{figure}

%%
\bibliographystyle{plainnat}
\bibliography{REFS}
\end{document}
