#' Prewhiten a series.
#' 
#' Remove (optionally) mean, trend, and Auto Regressive (AR) model
#' from the original series.
#'
#' The R-S multitapers do not exhibit the remarkable spectral-leakage 
#' suppression properties of the Thomson prolate tapers, 
#' so that in spectra with large dynamic range, 
#' power bleeds from the strong peaks into neighboring frequency bands of 
#' low amplitude -- spectral leakage. 
#' Prewhitening can ameliorate the problem, at least for red spectra 
#' [see Chapter 9, Percival and Walden (1993)]. 
#'
#' This function has essentially two modes of operation (detailed below):
#' \describe{
#' \item{\code{AR.max} < 1}{Remove (optionally) a mean and/or linear trend.}
#' \item{\code{AR.max} > 0}{Remove an autoregressive model}
#' }
#' In the second case,
#' the time series is 
# first
#' filtered in the time domain with a finite-impluse-response 
#' filter of \code{AR.max} terms. The filter is found by solving the Yule-Walker 
#' equations for 
#' which it is assumed the series was generated by an autoregressive process, up to
#' order \code{AR.max}.
# Next the multitaper spectral estimates are made on the filtered series. 
# Finally, the effect of the filter is removed by dividing out the spectrum of the 
# autoregressive process.
#
#' \subsection{Mean and trend (\code{AR.max < 1})}{
#' Power spectral density estimates can become badly biased
#' (especially at lower frequencies) if a signal of the form
#' \eqn{f(x) = A x + B} is not removed from the series.  
#' If \code{detrend=TRUE} a model of this form is removed over the entire series using a
#' linear least-squares estimator; in this case a mean value is removed
#' regardless of the logical state of \code{demean}.
#' To remove \emph{only} a mean value, set \code{detrend=FALSE} and (obviously) \code{demean=TRUE}.
#' }
#' \subsection{Auto Regressive (AR) innovations (\code{AR.max > 0})}{
#' When an autoregressive model is removed from a non-stationary series, the residuals
#' are known as 'innovations', and may be stationary (or very-nearly stationary).  
#' This function fits an AR model [order at least 1, but up to and including AR(\code{AR.max})] to the series 
#' by solving the Yule-Walker equations; however, AIC is used to estimate the highest significant
#' order, which means that higher-order components may not necessarily be fit.
#' The resulting innovations can be used to better estimate the stationary component
#' of the original signal, and possibly in an interactive editing method.
#'
#' A quick way to determine whether this may be needed for the series is to run \code{acf} on
#' it, and see if significant auto-correlations are found.
#' }
#'
#' @section NA values:
#' \code{NA} values are allowed.  If present, the function in the package
#' \code{zoo},
#' \code{na.locf}, which stands for "Last Observation Carried Forward",
#' is used to impute them with real numbers.
#'
#' @name prewhiten
#' @author A.J. Barbour <andy.barbour@@gmail.com> and Robert L. Parker
#' @keywords prewhiten autoregressive-innovations timeseries S3methods
#' @seealso \code{\link{psdcore}}, \code{\link{pspectrum}}
#' 
#' @param tser  vector; An object to prewhiten.
#' @param AR.max numeric; the maximum AR order to fit.
#' @param detrend  logical; Should a trend (and mean) be removed?
#' @param demean  logical; Should a mean value be removed?
#' @param plot  logical; Should the results be plotted?
#' @param verbose  logical; Should messages be printed?
#' @param x.fsamp sampling frequency (for non \code{ts} objects)
#' @param x.start start time of observations (for non \code{ts} objects)
#' @param ... variables passed to \code{prewhiten.ts} (for non \code{ts} objects)
#'
prewhiten <- function(tser, AR.max=0L, detrend=TRUE, demean=TRUE, plot=TRUE, verbose=TRUE) UseMethod("prewhiten")
#' @rdname prewhiten
#' @S3method prewhiten default
prewhiten.default <- function(tser, x.fsamp=1, x.start=c(1, 1), ...){
  Xts <- stats::ts(tser, frequency=x.fsamp, start=x.start)
  prewhiten(Xts, ...)
}
#' @rdname prewhiten
#' @S3method prewhiten ts
prewhiten.ts <- function(tser, AR.max=0L, detrend=TRUE, demean=TRUE, plot=TRUE, verbose=TRUE){
  # prelims
  stopifnot(stats::is.ts(tser))
  require(zoo)
  # some other info... needed?
  sps <- stats::frequency(tser)
  tstart <- stats::start(tser)
  n.o <- length(tser)
  ttime <- sps*n.o
  if (AR.max > 0) {
    AR.max <- as.integer(max(1, AR.max))
    if (verbose) message("autoregressive model fit (returning innovations)")
    # solves Yule-Walker equations
    #http://svn.r-project.org/R/trunk/src/library/stats/R/ar.R
    arfit <- stats::ar.yw(tser, aic=TRUE, order.max=AR.max, demean=demean)
    if (verbose) print(arfit)
    # ar returns a TS object
    tser.prew <- stats::as.ts(zoo::na.locf(arfit$resid))
  }
  # data.frame with fit params
  if (AR.max < 1){
    fit.df <- data.frame(xr=seq.int(from=1, to=n.o, by=1), 
                         xc=rep.int(1, n.o), 
                         y=tser)
    if (detrend){
      if (verbose) message("detrending (and demeaning)")
      X <- as.matrix(stats::residuals( stats::lm(y ~ xr, fit.df)))
    } else if (demean) {
      if (verbose) message("demeaning")
      X <- as.matrix(stats::residuals( stats::lm(y ~ xc, fit.df)))
    } else {
      X <- tser
      if (verbose) warning("nothing was done to the timeseries object")
    }
    tser.prew <- stats::ts(X, frequency=sps, start=tstart)
  }
  # optional plot
  if (plot) plot(stats::ts.union(tser, tser.prew), yaxs="i", xaxs="i", yax.flip=TRUE)
  return(invisible(tser.prew))
}
