# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname parabolic_weights
#' @export
parabolic_weights_rcpp <- function(ntap) {
    .Call('psd_parabolic_weights_rcpp', PACKAGE = 'psd', ntap)
}

