# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname psd-utilities
#' @export
#' @description \code{modulo_floor} returns the nearest \code{m}-length
#' value (downwards); this is different from \code{\link{nextn}}.
#' For example:
#' \code{1001} goes to \code{1000} for \code{m=2}
#' @param n integer; the number of terms
#' @param m integer; the modulo term
modulo_floor_rcpp <- function(n, m = 2L) {
    .Call('psd_modulo_floor_rcpp', PACKAGE = 'psd', n, m)
}

#' @rdname parabolic_weights
#' @export
parabolic_weights_rcpp <- function(ntap) {
    .Call('psd_parabolic_weights_rcpp', PACKAGE = 'psd', ntap)
}

#' @title Resample an fft using varying tapers
#' @param fftz complex; a vector representing the dual-length \code{\link[fftw]{FFT}}; see also \code{dbl}.
#' @param tapers integer; a vector of tapers
#' @param verbose logical; should messages be given?
#' @param dbl logical; should the code assume \code{fftz} is dual-length or singl-length?
#' @param tapcap integer; the maximum number of tapers which can be applied; note that the length is
#' automatically limited by the length of the series.
#' @export
resample_fft_rcpp <- function(fftz, tapers, verbose = TRUE, dbl = TRUE, tapcap = 1000L) {
    .Call('psd_resample_fft_rcpp', PACKAGE = 'psd', fftz, tapers, verbose, dbl, tapcap)
}

